project:
  type: website


lang: en  # Default language
languages:
  en: "English"
  es: "Español"

website:
  navbar:
    right:
      - text: "EN | ES"
        href: "index.es.html"
    class: fixed-top
    search: true
    left:
      - text: "Home"
        href: "index.html" 
      - text: "Our Story"
        href: "story.html"
      # - text: "Schedule"
      #   href: "schedule.html"
      - text: "Travel"
        href: "travel.html"
      - text: "FAQ"
        href: "faq.html"
      - text: "RSVP"
        href: "rsvp.html"

format:
  html:
    fig-align: center
    theme: 
      light: custom.scss  # Your custom SCSS file
      dark: themedark.scss
    grid:
      sidebar-width: 0px 
      margin-width: 0px
    lightbox: true
    toc: false
  revealjs:
    css: reveal.scss
    controls: true       # Keep navigation arrows
    # progress: false      # Hide progress bar (optional)
    slide-number: false  # Hide slide numbers
    # overview: false      # Disable the overview menu (hamburger)
    # auto-slide: 5000     # Auto-advance every 5 seconds
    # auto-slide-stoppable: false  # Prevent stopping the auto-slide manually
    # css: custom.scss  # Link to an external CSS file
     # Options: none, fade, slide, convex, concave, zoom
    transition-speed: slow
    transition: fade
      
    include-in-header:
      text: |
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">
        <style>
          body {
            font-family: "Playfair Display", sans-serif !important;
            font-weight: 300;
            margin-top: 70px;
            
          }
          html {
            scroll-behavior: smooth;
            scroll-padding-top: 80px;
          }
          .navbar {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            z-index: 1000; /* Ensures navbar stays above other elements */
          
          }
          
        </style>
      
