project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!es/*"


website:
  title: "Andrea & Juan's Wedding"
  search: false
  navbar:
    left:
      - text: "Home"
        href: index.html 
      - text: "Our Story"
        href: story.html
      - text: "Travel"
        href: travel.html
      - text: "FAQ"
        href: faq.html
      - text: "RSVP"
        href: https://pp.events/aaNmELQb
        target: _blank
    # right:
    #   - text: "ES"
    #     href: es/index.html
    #     id: lang-switch
        

format:
  html:
    theme:
      light: custom.scss
      dark: themedark.scss
    include-after-body: lang-switch.html
    toc: false
    lightbox: true  
