project:
  type: website
  output-dir: docs

website:

  navbar:
    left:
      - text: "Home"
        href: index.html 
      - text: "Our Story"
        href: story.html
      # - text: "Schedule"
      #   href: schedule.html
      - text: "Travel"
        href: travel.html
      - text: "FAQ"
        href: faq.html
      - text: "RSVP"
        href: https://pp.events/aaNmELQb
        target: _blank
    right:
      - text: "EN | ES"
        href: /es/index.html  # <-- Correct path
    class: fixed-top
    search: true

languages:
  en:
    name: English
    title: "Andrea & Juan's Wedding"
  es:
    name: Español
    title: "La boda de Andrea & Juan"
    site-url: /es/

format:
  html:
    fig-align: center
    theme: 
      light: custom.scss
      dark: themedark.scss
    grid:
      sidebar-width: 0px 
      margin-width: 0px
    lightbox: true
    toc: false

  revealjs:
    css: reveal.scss
    controls: true
    slide-number: false
    transition-speed: slow
    transition: fade

    include-in-header:
      text: |
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">
        <style>
          body {
            font-family: "Playfair Display", sans-serif !important;
            font-weight: 300;
            margin-top: 70px;
          }
          html {
            scroll-behavior: smooth;
            scroll-padding-top: 80px;
          }
          .navbar {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            z-index: 1000;
          }
        </style>
